### ISSUE TITLE
Investigate OOM errors in Circle CI

### ISSUE THREAD

**Issue by mkobit** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#42]
Builds keep failing with 137 exit code in the `junitPlatformTest` task. For example, https://circleci.com/gh/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/133

There are several JVM processes that are running that could be using all memory in the container.

* The client JVM for the wrapper
* The Gradle daemon for the current version
* The `JavaExec` forked process for `junitPlatformTest`
* The JUnit 5 `ConsoleLauncher`
* Gradle daemon spun up by GradleTestKit for each tested version (4.3, 4.4, and 4.4.1 right now)
* The `JenkinsRule` Jenkins process spun up in most tests.

I have a feeling some environment variables are propogating too much and attempting to over allocate rather than a single JVM running out of memory. Can investigate a little bit to see which thing is OOMing.
https://circleci.com/blog/how-to-handle-java-oom-errors/ may help.

The easiest solution to buy more time is to probably split up Circle CI stages by Gradle version tested

**Comment by mkobit** [comment]
Observations through JMC when using same env variables as Circle CI:

```yaml
JAVA_OPTS: -XX:+UseG1GC -Xmx1024m -Xms512m
# Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"
```

* Gradle 4.4.1 Wrapper executed for build - max 960 MB (about 1 GB), max at about 64MB
* Gradle 4.4.1 daemon (started for build) - max 1 GB
* `JavaExec` `ConsoleLauncher` - max 1 GB, max at around 320 MB
* Gradle 4.3 daemon - max 1 GB, max at around 320 MB
* Gradle 4.4 daemon - max 1 GB, max at around 320 MB
* Another Gradle 4.4.1 daemon - max 1 GB, max at around 320 MB
* a few short lived _Gradle Worker Daemon_ processes
